"use client";
import Link from "next/link";
import { ArrowLeft, CalendarDays, MapPin, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import LanguageToggle, { type Language } from "../components/LanguageToggle";
import "../globals.css";
const t={bn:{services:"সার্ভিস",providers:"প্রোভাইডার",login:"লগইন",back:"প্রোভাইডার তালিকায় ফিরে যান",eyebrow:"সার্ভিস রিকোয়েস্ট",title:"সার্ভিস বুক করুন",service:"সার্ভিস",date:"পছন্দের তারিখ",time:"পছন্দের সময়",area:"সার্ভিস এলাকা",areaPh:"যেমন: লাকসাম টাউন",address:"ঠিকানা",addressPh:"প্রোভাইডার কোথায় আসবেন?",need:"কী কাজ প্রয়োজন?",needPh:"সমস্যাটি সংক্ষেপে লিখুন...",send:"বুকিং রিকোয়েস্ট পাঠান",verified:"ভেরিফায়েড প্রোভাইডার",serves:"লাকসাম ও আশেপাশে সার্ভিস দেন",confirm:"কনফার্মেশন প্রয়োজন",price:"আনুমানিক শুরু মূল্য",success:"বুকিং রিকোয়েস্ট পাঠানো হয়েছে!",successSub:"Provider Dashboard-এ নতুন রিকোয়েস্ট দেখা যাবে।",view:"My Bookings দেখুন",another:"আরেকটি বুকিং"},en:{services:"Services",providers:"Providers",login:"Login",back:"Back to providers",eyebrow:"SERVICE REQUEST",title:"Book a service",service:"Service",date:"Preferred date",time:"Preferred time",area:"Service area",areaPh:"e.g. Laksam Town",address:"Address",addressPh:"Where should the provider come?",need:"What do you need?",needPh:"Briefly describe the problem...",send:"Send booking request",verified:"Verified provider",serves:"Serves Laksam & nearby areas",confirm:"Confirmation required",price:"Estimated starting price",success:"Booking request sent!",successSub:"The new request is now visible in Provider Dashboard.",view:"View My Bookings",another:"Make another booking"}};
const providerInfo:Record<string,{service:string;bn:string;price:string;area:string}>= {"Rahim Electric Service":{service:"Electrician",bn:"ইলেকট্রিশিয়ান",price:"৳500+",area:"Laksam Town"},"Kawsar AC Care":{service:"AC Technician",bn:"এসি টেকনিশিয়ান",price:"৳700+",area:"Laksam"},"Mizan Mobile Point":{service:"Mobile Repair",bn:"মোবাইল রিপেয়ার",price:"৳300+",area:"Bypass Road"},"Hasan Plumbing":{service:"Plumber",bn:"প্লাম্বার",price:"৳400+",area:"Azgara"},"Nayeem Laptop Care":{service:"Laptop Repair",bn:"ল্যাপটপ রিপেয়ার",price:"৳500+",area:"Laksam Bazar"},"Sabbir Home Care":{service:"Cleaner",bn:"ক্লিনার",price:"৳600+",area:"Laksam"}};
export default function BookingPage(){const[language,setLanguage]=useState<Language>("bn");const[sent,setSent]=useState(false);const[provider,setProvider]=useState("Rahim Electric Service");const[selectedService,setSelectedService]=useState("Electrician");const x=t[language];const info=providerInfo[provider]||providerInfo["Rahim Electric Service"];
useEffect(()=>{const params=new URLSearchParams(window.location.search);const p=params.get("provider");const s=params.get("service");if(p&&providerInfo[p])setProvider(p);if(s)setSelectedService(s)},[]);
useEffect(()=>{if(providerInfo[provider])setSelectedService(providerInfo[provider].service)},[provider]);
const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const booking={id:Date.now(),customer:String(form.get("name")||"Customer"),service:String(form.get("service")||selectedService),date:String(form.get("date")||"Not specified"),time:String(form.get("time")||"09:00 AM"),area:String(form.get("area")||"Laksam"),address:String(form.get("address")||""),need:String(form.get("need")||""),status:"Pending",provider};const existing=JSON.parse(window.localStorage.getItem("laksam-bookings")||"[]");window.localStorage.setItem("laksam-bookings",JSON.stringify([booking,...existing]));window.dispatchEvent(new Event("laksam-bookings-updated"));setSent(true)};
return <main className="page-shell"><header className="site-header"><Link className="brand" href="/">Laksam <span>Local Service</span></Link><nav><Link href="/services">{x.services}</Link><Link href="/providers">{x.providers}</Link></nav><div className="header-actions"><LanguageToggle onChange={setLanguage}/><Link className="header-cta" href="/login">{x.login}</Link></div></header><section className="booking-wrap"><Link className="back-link" href="/providers"><ArrowLeft size={16}/> {x.back}</Link><div className="booking-layout">{sent?<div className="form-card booking-success"><div className="success-icon">✓</div><p className="eyebrow">{language==="bn"?"সফল":"SUCCESS"}</p><h1>{x.success}</h1><p className="form-subtitle">{x.successSub}</p><div className="success-actions"><Link className="primary-btn" href="/bookings">{x.view}</Link><button className="secondary-btn" type="button" onClick={()=>setSent(false)}>{x.another}</button></div></div>:<form className="form-card" onSubmit={submit}><p className="eyebrow">{x.eyebrow}</p><h1>{x.title}</h1><p className="form-subtitle">{provider}-এর কাছে {language==="bn"?"আপনার রিকোয়েস্ট পাঠান":"send your service request."}</p><label>{language==="bn"?"আপনার নাম":"Your name"}<input name="name" required placeholder={language==="bn"?"আপনার নাম লিখুন":"Your name"}/></label><label>{x.service}<input name="service" value={language==="bn"?info.bn:selectedService} readOnly /></label><input type="hidden" name="service" value={selectedService}/><label>{x.date}<input name="date" required type="date"/></label><label>{x.time}<select name="time"><option>09:00 AM</option><option>12:00 PM</option><option>03:00 PM</option><option>06:00 PM</option></select></label><label>{x.area}<input name="area" required placeholder={x.areaPh} defaultValue={info.area}/></label><label>{x.address}<textarea name="address" required placeholder={x.addressPh} rows={3}/></label><label>{x.need}<textarea name="need" required placeholder={x.needPh} rows={4}/><button className="primary-btn" type="submit">{x.send}</button></form>}<aside className="booking-summary"><div className="summary-avatar">{provider[0]}</div><h2>{provider}</h2><p>{language==="bn"?info.bn:info.service} · {info.area}</p><div className="summary-row"><ShieldCheck size={17}/><span>{x.verified}</span></div><div className="summary-row"><MapPin size={17}/><span>{x.serves}</span></div><div className="summary-row"><CalendarDays size={17}/><span>{x.confirm}</span></div><div className="price-box"><span>{x.price}</span><strong>{info.price}</strong></div></aside></div></section></main>}
